version: 2.1
orbs:
  slack: circleci/slack@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.4

filters: &filters
  tags:
    only: /.*/

jobs:
  integration-test-templates:
    parameters:
      runner:
        type: executor
        default: cimg
    executor: <<parameters.runner>>
    steps:
      - checkout
      - run: printf '%s\n' "Hello There!" > /tmp/msg
      - slack/notify:
          debug: true
          step_name: "Custom template with group mention"
          event: always
          custom: |
            {
              "type": "mrkdwn",
              "text": "$(cat /tmp/msg)"
            }

workflows:
  test-deploy:
    jobs:
      - integration-test-templates:
          context: SLACK_NOTIFICATIONS_TEST
          filters: *filters
          matrix:
            parameters:
              runner: [cimg, mac, alpine, windows]
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/slack
          vcs-type: << pipeline.project.type >>
          pub-type: production
          enable-pr-comment: true
          github-token: GHI_TOKEN
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - integration-test-templates
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
executors:
  cimg:
    docker:
      - image: cimg/base:stable
  mac:
    macos:
      xcode: 11.7.0
  alpine:
    # This image contains both CURL and JQ
    docker:
      - image: dwdraju/alpine-curl-jq
  windows:
    machine:
      image: windows-server-2019-vs2019:current
      resource_class: windows.medium
      shell: bash.exe
